const SAVE_VIDOES = 'SAVE_VIDOES';
const REMOVE_VIDEO = 'REMOVE_VIDEO';
const MODAL_VALUE = 'MODAL_VALUE';
const DELETED_VIDEOS = 'DELETED_VIDEOS';
export { SAVE_VIDOES,REMOVE_VIDEO,MODAL_VALUE,DELETED_VIDEOS };
